#!/bin/sh

api="http://169.254.169.254/latest/meta-data/"
path=`dirname $0`

setenv=$path/setenv.sh
if [ ! -r $setenv ]; then
    echo "$setenv not found"
    exit 1
fi
source $setenv

update()
{
    key=$1
    if [ "$key" == "" ]; then
        return 1;
    fi

    value=`curl --fail --silent $api/$key`
    if [ "$value" != "" ]; then
        cat > $path/$key <<EOF
#!/bin/sh
# This is auto genete script.
#
# date: `date`
# by:   $0
echo $value
EOF
	chmod +x $path/$key
        echo "$key : $path/$key updated."
    else
        rm $path/$key
        echo "$key : api failed"
    fi

    return 0
}

echo "get metadata info"
keys="ami-id ami-manifest-path hostname instance-id instance-type local-hostname local-ipv4 public-hostname public-ipv4"
for key in $keys; do
    update $key
done

echo "get volume info"
instance=`$path/instance-id`
if [ -f $path/volume ]; then
    rm $path/volume
fi
ec2-describe-volumes \
    | grep ATTACHMENT \
    | grep attached \
    | grep $instance \
    | while read t1 volume instance t2 status t3; do
if [ "$volume" != "" ]; then
        cat > $path/volume <<EOF
#!/bin/sh
# This is auto genete script.
#
# date: `date`
# by:   $0
echo $volume
EOF
        chmod +x $path/volume
        echo "volume : $path/volume updated."
fi
done
if [ ! -f $path/volume ]; then
    echo "no attached volume"
fi
